export const TOURNAMENT_SERIES_EVENTS_PER_PAGE = 20;
export const TOURNAMENT_SERIES_LEADERBOARD_SIZE = 50;

export const TOURNAMENT_ORGANIZATION = {
	DESCRIPTION_MAX_LENGTH: 1_000,
	BAN_REASON_MAX_LENGTH: 200,
	MAX_BANNED_USERS: 100,
};
