export const ART_PER_PAGE = 14;

export const ART = {
	DESCRIPTION_MAX_LENGTH: 140,
	LINKED_USERS_MAX_LENGTH: 10,
	THUMBNAIL_WIDTH: 640,
	TAG_MAX_LENGTH: 100,
	TAGS_MAX_LENGTH: 25,
};

export const NEW_ART_EXISTING_SEARCH_PARAM_KEY = "art";
export const FILTERED_TAG_KEY_SEARCH_PARAM_KEY = "tag";
